spring.application.name=resumeIQ

spring.datasource.url=${DATABASE_URL:jdbc:mysql://localhost:3306/resumeiq_db?createDatabaseIfNotExist=true}
spring.datasource.username=${DATABASE_USERNAME:root}
spring.datasource.password=${DATABASE_PASSWORD:root}
spring.datasource.driver-class-name=${DATABASE_DRIVER:com.mysql.cj.jdbc.Driver}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

claude.api.key=${GROQ_API_KEY}

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

server.port=${PORT:8080}
